### ISSUE TITLE
Quarto template update: add in yaml parameters for table alignment

### ISSUE THREAD

**Issue by tashapiro** [WA-Department-of-Agriculture/soil-health-report-generator#72]
Add back in code chunk:
```

knitr: 
  opts_chunk:
    dev: "ragg_png"
    tbl.cap: NULL
    ft.align: "left"
fig-align: left
fig-width: 6
fig-height: 3.5
fig-dpi: 300
```
